### ISSUE TITLE
Authentical required to clone?

### ISSUE THREAD

**Issue by baqwas** [Azure-Samples/iot-hub-c-raspberrypi-getstartedkit#27]
The following clone command on an _updated _RPi2 (**Jessie
![iot-hub-c-raspberrypi-getstartedkit clone issue](https://cloud.githubusercontent.com/assets/7071255/15099802/63d36df2-1525-11e6-9e91-2864113ba4dd.PNG)
**) shows authentication prompts:
git clone https://github.com/Azure-Samples/iot-hub-c-raspberrypi-getstartedkit.git

Username for 'https://github.com':
Password for 'https://github.com':

Did not experience the same when I reproduced the operation in **Windows 10 **(_worked fine in the latter environment without having to furnish credentials_).

Any suggestions on a workaround (since my own GitHub credentials were not accepted) yet I am able to use the same to post this inquiry. Thanks.

**Comment by anhashia** [comment]
https://github.com/Azure-Samples/iot-hub-c-raspberrypi-getstartedkit.git is a public end point using Https (HTTP over SSL) connection. I don't get prompted for user name and password on Windows 10 or on Ubuntu. I didn't  have chance to try it on Raspberry Pi for local reproduction of your issue yet.

Even if it asks for user name and password, it will be more specific to GitHub functionality rather than anything to do with Azure sample code repository.Look like this is covered under 
https://help.github.com/articles/why-is-git-always-asking-for-my-password/

**Comment by anhashia** [comment]
Unable to reproduce the issue on Raspbian on Raspberry Pi. Didn’t get prompted for user name and password.
